apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "public-test.fullname" .) }}
  labels:
    {{- include "public-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "public-test.name" . }}
    release: {{ .Release.Name }}