replicaCount: 1

image:
  repository: ghcr.io/comet-ml/public-test
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: public-test
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

nginx:
  service:
    type: ClusterIP
  ingress:
    enabled: false