name: Build

on:
  workflow_dispatch:
  push:
    branches: 
        - 'main'
    paths-ignore: 
        - "charts/**"


jobs:
    build:
        runs-on: ubuntu-latest
        env:
            LOGIN: ${{ secrets.DOCKER_USERNAME }}
            NAME: ${{ secrets.DOCKER_NAME }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.1
            with:
              fetch-depth: 1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
                
          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io/my-org
                username: "github-actions"
                password: ${{ secrets.GITHUB_TOKEN }}
            
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                tags: |
                    ghcr.io/comet-ml/public-test:latest
                    ghcr.io/comet-ml/public-test:${{ github.run_number }}


